# Generated by Django 5.2.7 on 2025-11-10 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('unit_price', models.FloatField(null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('discount_percent', models.FloatField(null=True)),
                ('tax_percent', models.FloatField(null=True)),
                ('subtotal', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_info', to='sales.customermodel')),
            ],
        ),
    ]
